version: 0.0
os: linux 
files:
  - source: config/setenv.txt
    destination: /usr/share/tomcat/conf/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root